### ISSUE TITLE
some properties are scoped by class with dot syntax while they are really the same property

### ISSUE THREAD

**Issue by denevers** [opengeospatial/GeoSciML#8]
@sgrellet (BTW, Abdel should have an account ...)

Those two properties 

`gsmlb:GeologicFeature.observationMethod`

and

`gsmlb:MappedFeature.observationMethod`

are really the same properties with two possible domains (MappedFeature and GeologicFeature).  In this case, (and maybe some others ?), it should not be scope with a "." syntax

**Comment by afeliachi** [comment]
@denevers Thank you for noticing this. I was about to unify these two properties, I would like to have one definition for them. What would it be in this case?

**Comment by denevers** [comment]
GeologicFeature's is quite generic and might cover MappedFeature's usage 

> specifies the approach to acquiring the collection of attribute values that constitute an individual feature instance (e.g. point count, brunton compass on site, air photo interpretation, field observation, hand specimen, laboratory, aerial photography, creative imagination)

MappedFeature definition just says : "describing how the spatial extent of the mapped feature was determined." which is - I think - covered by the above definition.

**Comment by afeliachi** [comment]
Thanks Eric, will do it.

**Comment by smrgeoinfo** [comment]
the observation method for a mapped feature is concerned with how the spatial extent was mapped (air photo, ground traverse, some published source...)
Observation method for a geologicFeature has to do with how the geologic properties of the feature were determined-- lithology, age, fault slip. 
There are separate CGI GTWG vocabularies for these properties-- MappedFeatureObservationMethod and FeatureObservationMethod.

**Comment by denevers** [comment]
You bring an interesting point.  Is having different vocabularies makes them different properties ?  On the constrain side, the vocabulary that is to be used is defined by the community, not the model.  We had a use case (in GIN) where the lithology of a GeologicUnit used a different vocabulary in a Well context than a Map context.  But this is slightly different because it's two properties having the same semantic but owned by two different classes.

BTW : Some of the vocabularies we have in GeoSciML have xyzTerm as property type , but for some reason I can't remember, both observationMethod are swe:Category (was there a rule to used either one ?)
